### ISSUE TITLE
大佬，你这个程序怎么关闭停止

### ISSUE THREAD

**Issue by NJCHello** [dozer47528/home-config#1]
大佬，你这个程序怎么关闭停止，我在自己电脑上执行了一下./setup，导致好多配置都错乱了，不知道怎么停和恢复

**Comment by dozer47528** [comment]
> 大佬，你这个程序怎么关闭停止，我在自己电脑上执行了一下./setup，导致好多配置都错乱了，不知道怎么停和恢复

这是我私人的配置仓库，不建议直接使用，可能会导致自己的配置丢失。

@NJCHello N
